'use strict';

const ErrorCodes = {
  BOOK_CONFIG_MISSING: 'BOOK_CONFIG_MISSING',
  BOOK_CONFIG_INVALID: 'BOOK_CONFIG_INVALID',
  WORKFLOW_CONFIG_INVALID: 'WORKFLOW_CONFIG_INVALID',
  PHASE_UNSUPPORTED: 'PHASE_UNSUPPORTED',
  PHASE_DEPENDENCY_MISSING: 'PHASE_DEPENDENCY_MISSING',
  GATE_UNSUPPORTED: 'GATE_UNSUPPORTED',
  GATE_FAILED: 'GATE_FAILED',
  DATASET_PATH_INVALID: 'DATASET_PATH_INVALID',
  BACKUP_FAILED: 'BACKUP_FAILED',
  WRITE_DENIED: 'WRITE_DENIED',
  PROVIDER_NOT_CONFIGURED: 'PROVIDER_NOT_CONFIGURED',
  NETWORK_UNAVAILABLE: 'NETWORK_UNAVAILABLE',
  HTML_PARSE_FAILED: 'HTML_PARSE_FAILED',
  EPUB_INVALID: 'EPUB_INVALID',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
};

module.exports = ErrorCodes;
